import { COLOR_HEX, createDefaultProject, SYMBOL_LABELS } from '@lp-sketch/core/model/defaultProject'
import type { MaterialColor, SymbolType, Tool } from '@lp-sketch/core/types/project'
import type { AppController } from '../../context/AppController'

const noop = () => {}

const TOOL_OPTIONS: Array<{ id: Tool; label: string }> = [
  { id: 'select', label: 'Select' },
  { id: 'multi_select', label: 'Multi' },
  { id: 'pan', label: 'Pan' },
  { id: 'line', label: 'Linear' },
  { id: 'arc', label: 'Arc' },
  { id: 'curve', label: 'Curve' },
  { id: 'linear_auto_spacing', label: 'Linear AT' },
  { id: 'arc_auto_spacing', label: 'Arc AT' },
  { id: 'symbol', label: 'Component' },
  { id: 'legend', label: 'Legend' },
  { id: 'general_notes', label: 'General Notes' },
  { id: 'text', label: 'Text' },
  { id: 'dimension_text', label: 'Dim Text' },
  { id: 'arrow', label: 'Arrow' },
  { id: 'calibrate', label: 'Calibrate' },
  { id: 'measure', label: 'Measure' },
  { id: 'measure_mark', label: 'Mark' },
]

const COLOR_OPTIONS: MaterialColor[] = ['green', 'blue', 'purple', 'red']

/**
 * A static, fully populated controller for mounting shells and blocks outside
 * `App`. Every action is a no-op; pass `overrides` to observe calls or vary state.
 */
export function createFixtureController(overrides: Partial<AppController> = {}): AppController {
  return {
    project: createDefaultProject(),
    hasPdf: false,
    supportsNativeFileDialogs: false,
    tool: 'select',
    selectedKind: null,
    multiSelectionCount: 0,
    toolOptions: TOOL_OPTIONS,
    lineStart: null,
    lineContinuous: false,
    curveContinuous: false,
    arcStart: null,
    arcEnd: null,
    dimensionStart: null,
    dimensionEnd: null,
    dimensionShowLinework: true,
    linearAutoSpacingMaxInput: '20',
    linearAutoSpacingVerticesCount: 0,
    arcAutoSpacingMaxInput: '20',
    arcAutoSpacingTargetSet: false,
    touchCornerMode: 'outside',
    activeSymbol: 'air_terminal',
    selectedSymbolType: null,
    downleadVerticalFootagePlacementInput: '0',
    downleadVerticalFootageSelectedInput: '',
    activeSymbolLetter: 'A',
    legendCustomSuffixInput: '',
    symbolOptions: Object.keys(SYMBOL_LABELS) as SymbolType[],
    symbolLabels: SYMBOL_LABELS,
    textDraftInput: '',
    textBackgroundMask: false,
    selectedTextBackgroundMask: null,
    arrowStart: null,
    symbolDirectionStart: null,
    selectedLegendPlacement: null,
    selectedGeneralNotesPlacement: null,
    colorOptions: COLOR_OPTIONS,
    colorHex: COLOR_HEX,
    pdfTransparency: 0,
    currentPage: 1,
    pageCount: 1,
    canGoToPreviousPage: false,
    canGoToNextPage: false,
    manualScaleInchesInput: '',
    manualScaleFeetInput: '',
    manualScaleDirty: false,
    measureTargetDistanceInput: '',
    calibrationPointsCount: 0,
    calibrationPendingDistancePt: null,
    calibrationDistanceInput: '',
    calibrationInputError: '',
    currentScaleInfo: 'Scale: unset',
    historyPastCount: 0,
    historyFutureCount: 0,
    canBringSelectedToFront: false,
    canSendSelectedToBack: false,
    canDeleteSelection: false,
    statusMessage: '',
    errorMessage: '',
    stageCursor: 'pointer',
    calibrationPreview: null,
    lineSegmentDistanceLabel: null,
    linePathTotalDistanceLabel: null,
    measureDistanceLabel: null,
    markSpanDistanceLabel: null,
    linearAutoSpacingPathDistanceLabel: null,
    selectionDebugEnabled: false,
    onRefocusCanvasFromInputCommit: noop,
    onSetProjectName: noop,
    onImportPdf: noop,
    onImportPdfPicker: noop,
    onImportPdfDrop: noop,
    onSaveProject: noop,
    onLoadProject: noop,
    onLoadProjectPicker: noop,
    onExportImage: noop,
    onExportPdf: noop,
    onOpenReportDialog: noop,
    onSelectTool: noop,
    onSetLineContinuous: noop,
    onSetCurveContinuous: noop,
    onResetArc: noop,
    onSetLinearAutoSpacingMaxInput: noop,
    onFinishLinearAutoSpacing: noop,
    onResetLinearAutoSpacingTrace: noop,
    onSetArcAutoSpacingMaxInput: noop,
    onApplyArcAutoSpacing: noop,
    onClearArcAutoSpacingTarget: noop,
    onSetTouchCornerMode: noop,
    onClearMeasurement: noop,
    onResetMeasureMarkSpan: noop,
    onClearAllMarks: noop,
    onSetActiveSymbol: noop,
    onSetDownleadVerticalFootagePlacementInput: noop,
    onSetDownleadVerticalFootageSelectedInput: noop,
    onCommitDownleadVerticalFootageSelectedInput: noop,
    onSetTextDraftInput: noop,
    onSetTextBackgroundMask: noop,
    onSetActiveSymbolLetter: noop,
    onSetLegendCustomSuffixInput: noop,
    onClearLegendCustomSuffix: noop,
    onResetArrow: noop,
    onResetDimensionText: noop,
    onSetDimensionShowLinework: noop,
    onEditSelectedLegend: noop,
    onEditSelectedGeneralNotes: noop,
    onSetActiveClass: noop,
    onSetActiveColor: noop,
    onSetDesignScale: noop,
    onPreviewPdfTransparency: noop,
    onCommitPdfTransparency: noop,
    onGoToPreviousPage: noop,
    onGoToNextPage: noop,
    onSetSnapEnabled: noop,
    onSetAutoConnectorsEnabled: noop,
    onSetAutoConnectorType: noop,
    onSetAngleSnapEnabled: noop,
    onSetLayerVisible: noop,
    onSetLayerSublayerVisible: noop,
    onSetManualScaleInchesInput: noop,
    onSetManualScaleFeetInput: noop,
    onSetMeasureTargetDistanceInput: noop,
    onSetCalibrationDistanceInput: noop,
    onApplyCalibration: noop,
    onCancelCalibration: noop,
    onApplyManualScale: noop,
    onBringSelectedToFront: noop,
    onSendSelectedToBack: noop,
    onDeleteSelection: noop,
    onUndo: noop,
    onRedo: noop,
    onSetSelectionDebugEnabled: noop,
    onSetQuickAccessEditingContextActive: noop,
    ...overrides,
  }
}
